const testHarvestStatus = require('./utils/route-status').harvest;
const testPublisherStatus = require('./utils/route-status').publisher;
const testDatasetStatus = require('./utils/route-status').datasetStandard;
const updateEnv = require('./utils/update-env');

module.exports = async page => {
    console.log('Creating a mock harvest source...');

    if (await testPublisherStatus(page) === 404) {
        throw new Error('Cannot find publisher in your specified domain and therefore cannot create harvest source. Please create or generate a publisher before running the harvest source setup script.');
    }

    if (await testHarvestStatus(page) === 404) {
        await Promise.all([
            page.goto(`${process.env.DOMAIN}/harvest/new`),
            page.waitForNavigation() 
        ]);

        await page.evaluate(() => {
            document.getElementById('field-url').value = 'https://ckan-static-mock-harvest-source.cloudapps.digital/';
            document.getElementById('field-title').value = 'Mock harvest source';
            document.getElementById('field-name').value = 'mock-harvest-source';
            document.getElementById('field-notes').value = 'Mock harvest source';
        });

        await Promise.all([
            page.click('button[type="submit"]'),
            page.waitForNavigation()
        ]);

        console.log('Checking successful mock harvest source generation...');

        if (await testHarvestStatus(page) === 200) {
            console.log('Mock harvest source created successfully!');
        } else {
            throw new Error('Unable to verify existence of mock harvest source after automated creation. Please check that your local instance of docker-ckan is running properly and try again.');
        }

    } else {
        console.log('Mock harvest source already exists! Skipping harvest generation.');
    }

    console.log('Triggering harvest job...');

    if (await testDatasetStatus(page) === 404) {
        await Promise.all([
            page.goto(`${process.env.DOMAIN}/harvest/admin/mock-harvest-source`),
            page.waitForNavigation() 
        ]);
    
        await page.click('a[data-module="confirm-action"]');
        await page.reload();
    
        console.log('Checking successful harvest job trigger...');
    
        if (await testDatasetStatus(page) === 200) {
            console.log('Harvest source triggered successfully!');
        } else {
            throw new Error('Unable to verify that mock harvest source job was triggered. Please check that your local instance of docker-ckan is running properly and try again.');
        }
    } else {
        console.log('The dataset generated by the mock harvest job already exists! Skipping triggering of harvest job.')
    }

    console.log('Retreiving id of first dataset resource... These will be written to your .env file.');

    const resourceId = await page.evaluate(() => document.querySelector('.resource-item').dataset.id);
    await updateEnv([resourceId], ['STANDARD_RESOURCE']);

    console.log('.env file updated with the resource id. Harvest setup is complete!');
}